#!/bin/csh -f
#PBS -j eo
#PBS -r n
#PBS -l nodes=1:ppn=1
hostname
date

# This block of commands is server-specific
setenv g09root /home/serg/Gaussian/g09D01_nex_pgf/
source $g09root/g09/bsd/g09.login

# Here you may want to change running directory and filename extensions
setenv RUN_DIR ~/gaussian/
setenv GAUSS_SCRDIR /scratch/$LOGNAME/$PBS_JOBNAME
mkdir -p $GAUSS_SCRDIR
cd ${RUN_DIR}
g09 < $PBS_JOBNAME.gau > $PBS_JOBNAME.out
rm -rf $GAUSS_SCRDIR
date
